development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: authlogic_example_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: authlogic_example_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: authlogic_example_production
  pool: 5
  username: root
  password:

